name: Flutter Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.4

      - name: Install dependencies
        run: 
          flutter pub get

      - name: Run Flutter lint
        run:
          flutter analyze

      - name: Run Flutter tests
        run:
          flutter test